global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: clickhouse
    static_configs:
      - targets: ["clickhouse-exporter:9116"]
  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
