global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus-under-test
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: victoriametrics
    metrics_path: /metrics
    static_configs:
      - targets: ["victoriametrics:8428"]
